name: Android Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Generate file name env var
        run: |
          VERSION_NAME='testing'
          DATE=$(date +'%d.%m.%Y')
          BRANCH_NAME=${GITHUB_REF##*/}
          MESSAGE=$(cat << EOF
          AppName-release-${VERSION_NAME}-${BRANCH_NAME}-${DATE}
          EOF)
          echo OUTPUT_NAME=$MESSAGE >> $GITHUB_ENV

      - name: Assemble app debug APK
        run: bash ./gradlew assembleRelease --stacktrace
      - name: Verify APK existence
        run: |
          echo "Checking if the APK file exists..."
          ls -al ./app/build/outputs/apk/release/
      - name: Rename APK 
        run:
          mv "./app/build/outputs/apk/release/app-release-unsigned.apk" "./app/build/outputs/apk/release/${{ env.OUTPUT_NAME }}.apk"
      - name: Verify APK existence
        run: |
          echo "Checking if the APK file exists..."
          ls -al ./app/build/outputs/apk/release/
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUTPUT_NAME }}
          path: app/build/outputs/apk/release/${{ env.OUTPUT_NAME }}.apk
      - name: Release APK
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.TOKEN}}
        with:
          title: "v1.0.1"
          workdir: "app/build/outputs/apk/release/"
          tag: "v1.0.1"
          
